openapi: 3.0.1
info:
  title: EWSActivity Apis specification
  description: OpenAPI Spec for EWS Activity APIs
  contact:
    name: Partner APIs
    url: https://confluence.expedia.biz/pages/viewpage.action?pageId=833040081
    email: autobots@expedia.com
  version: v3
  x-eg-lifecycle: LIVE
  x-eg-tags: ["Partner", "Activities", "EWS", "ActivitySearch", "ActivityDetails", "ActivityLinks"]
servers:
  - url: 'https://apim.expedia.com'
    description: Production Server
tags:
  - name: Activities List
  - name: Activities Details
paths:
  /activities/listings:
    get:
      tags:
        - Activities List
      description: The Activities Search API allows partners to search for Expedia Activity inventory.
      operationId: get-activity-listings
      parameters:
        - name: location
          in: query
          description: |-
            Can be a city name, street address, three-letter IATA Airport Code or a landmark name.
            (If the value submitted does not clearly identify a single location the API may returne a disambiguation response that lists possible options)
          schema:
            type: string
          example: shenzhen
        - name: geoLocation
          in: query
          description: |-
            The latitude and longitude values identifying the center point of a search radius (circle).
            North latitude will be represented by a positive value. South latitude by a negative value.
            East longitude will be represented by a positive value. West longitude by a negative value.
            The latitude and longitude values are joined together with a comma (,) character.
          schema:
            type: string
          example: 25.070062,-121.538306
        - name: startDate
          in: query
          description: |-
            Start date for the activity window in YYY-MM-DD format.
            If an endDate value is supplied there must also be a startDate.
            default: currentDate
          schema:
            type: string
            format: date
          example: 2021-10-01
        - name: endDate
          in: query
          description: |-
            End date for the activity window in YYY-MM-DD format.
            default: "startDate+14"
          schema:
            type: string
            format: date
          example: 2021-10-10
        - name: locale
          in: query
          description: |-
            locale is composed of language identifier and region identifier, connected by "_" that specifies the language in which the response will be returned.
            example: "fr_FR" refers to French as spoken in France, while "fr_CA" refers to French as spoken in Canada.
            For a full list of supported locales please refer to the link at the bottom of the page.
          schema:
            type: string
          example: en_US
        - name: links
          in: query
          description: |-
            Comma-separated list to specify the types of HATEAOS links returned in the API Response.
            WD (deep link URL to web infosite)
            AD (details API query)
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
                - WD
                - AD
          example: WD
        - name: Key
          in: header
          description: |-
            Unique identifier assigned to partner.
            Required for all requests.
            Obtained from Expedia Account Manager or representative.
          required: true
          schema:
            type: string
          example: X99X9X9-99XX-9XX9-X999-99XX99X9X999X
        - name: Partner-Transaction-Id
          in: header
          description: Partner-generated identifier.
          required: true
          schema:
            type: string
          example: BestTravel-123456-798101112
      responses:
        '500':
          description: |-
            Server side error i.e connection timeout while talking to downstream services, downstream returned error. The server responds back with this Http "
                      + "response code and with the appropriate JSON error response.
          content:
            application/vnd.exp-activity.v3+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '200':
          description: successful
          content:
            application/vnd.exp-activity.v3+json:
              schema:
                $ref: '#/components/schemas/ActivityListingsResponse'
              example:
                TransactionId: f06edfa3-27f4-44e6-838c-b8dd3d0a3210
                Count: 1
                Location: shenzhen, gd
                StartDate: 2021-08-01
                EndDate: 2021-08-08
                Categories:
                  - Count: 1
                    CategoryName: Cruises & Water Tours
                    CategoryDisplayName: Cruises & Water Tours
                    GroupName: Tours
                    GroupDisplayName: Tours
                Activities:
                  - Id: 166597
                    Title: 'Faster Than Skip-the-Line: Vatican, Sistine Chapel & St.
                    Peter''s Tour'
                    Description: Enjoy 5 of Seattle's most popular attractions with a multi-ticket booklet that’s valid for 9 consecutive days. This pass is perfect if you want to explore the city on your schedule, craft your own itinerary, and visit the city’s can’t-miss museums and most iconi..
                    Media:
                      - Type: "1"
                        Size: t
                        Url: http://a.travel-assets.com/ lxweb/ media-vault/ 166597_m.jpeg? v=104741
                    Categories:
                      - Walking & Bike Tours
                    Duration: PT3H0M
                    CancellationPolicy:
                      FreeCancellation: true
                    Price:
                      Category: Adult
                      TotalRate:
                        Value: 100
                        Currency: USD
                    ReferencePrice:
                      Category: Adult
                      TotalRate:
                        Value: 110
                        Currency: USD
                    Savings:
                      percentage: 42
                      amount:
                        Value: "9"
                        Currency: USD
                    Redemption:
                      Type: Voucherless
                      Locations:
                        - Address:
                            Address1: 99 Union St
                            City: Seattle
                            PostalCode: "431625"
                            Province: WA
                            Country: USA
                          GeoLocation:
                            Latitude: "47.60772"
                            Longitude: -122.33936
                    Locations:
                      - Address:
                          Address1: 99 Union St
                          City: Seattle
                          PostalCode: "431625"
                          Province: WA
                          Country: USA
                        GeoLocation:
                          Latitude: "47.60772"
                          Longitude: -122.33936
                    Supplier:
                      Name: City Wonders
                    RecommendationScore: 90
                    ReviewCount: 100
                    Links:
                      WebDetails:
                        Href: https://www.expedia.com/things-to-do/space-needle-observation-deck-admission.a193678.activity-details?srp=true&location=sea
                      ApiDetails:
                        Accept: application/vnd.exp-activity.v3+json
                        Method: GET
                        Href: https://apim.expedia.com/activities/details/CgUyMDIzMBIyCgkyMDEzMDQ1OTYSCTIwOTc3MjcwOBoCMjQqCjIwMTctMTEtMTkyCjIwMTctMTEtMjUqAwoBMg
        '400':
          description: |-
            Client side error while providing the request i.e bad / invalid input parameters. The server responds back with "
                      + "this Http response code and with the appropriate JSON error response.
          content:
            application/vnd.exp-activity.v3+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Errors:
                  - Code: AMBIGUOUS_LOCATION
                    Description: Multiple search locations found.
                    LocationKeyword: 99UnionSt
                    LocationOptions:
                      - ShortName: Union Grove, Wisconsin, United States of America
                        Address: Milwaukee (and vicinity), Wisconsin, United States of America
                        RequestedLocation: 'United States'
                        Locations:
                          - Name: Portland (and vicinity)
                            LocationId: seat001
                TransactionId: cecf62c8-c103-4181-b09d-53c7190d1c48
        '404':
          description: No Route matched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                no Route matched:
                  value: |-
                    {
                        "message": "no Route matched with those values"
                    }
        '429':
          description: API rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                API rate limit exceeded:
                  value: |-
                    {
                        "message": "API rate limit exceeded"
                    }
        '401':
          description: Unauthorized or Invalid authentication credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                unauthorized:
                  value: |-
                    {
                        "message": "Unauthorized"
                    }
                Invalid authentication credentials:
                  value: |-
                    {
                        "message": "Invalid authentication credentials"
                    }
        '403':
          description: cannot consume this service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                cannot consume this service:
                  value: |-
                    {
                        "message": "You cannot consume this service"
                    }
        '503':
          description: name resolution failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                name resolution failed:
                  value: |-
                    {
                        "message": "name resolution failed"
                    }
        '504':
          description: upstream server is timing out
          content:
            text/plain:
              examples:
                upstream server is timing out:
                  value: The upstream server is timing out
      security:
        - basicSchema: []
  /activities/details/{offerToken}:
    get:
      tags:
        - Activities Details
      description: The Activity Details API provides detailed information about one selected activity.
      operationId: get-activity-details
      parameters:
        - name: offerToken
          in: path
          description: the offerToken of a activity
          required: true
          schema:
            type: string
          example: CgY0NzY2NzgSCjIwMjEtMDUtMDIaCjIwMjEtMDUtMDc
        - name: locale
          in: query
          description: |-
            locale is composed of language identifier and region identifier, connected by "_" that specifies the language
            in which the response will be returned.
            example: "fr_FR" refers to French as spoken in France, while "fr_CA" refers to French as spoken in Canada.
            For a full list of supported locales please refer to the link at the bottom of the page.
          schema:
            type: string
          example: en_US
        - name: Key
          in: header
          description: |-
            Unique identifier assigned to partner.
            Required for all requests.
            Obtained from Expedia Account Manager or representative.
          required: true
          schema:
            type: string
          example: X99X9X9-99XX-9XX9-X999-99XX99X9X999X
        - name: Partner-Transaction-Id
          in: header
          description: Partner-generated identifier.
          required: true
          schema:
            type: string
          example: BestTravel-123456-798101112
      responses:
        '400':
          description: |-
            Client side error while providing the request i.e bad / invalid input parameters. The server responds back with "
                      + "this Http response code and with the appropriate JSON error response.
          content:
            application/vnd.exp-activity.v3+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Errors:
                  - Code: INVALID_LINKS
                    Description: 'Invalid links. Allowed value are:[WS, AD, WD].'
                TransactionId: 583b7277-772a-4802-8ac7-bcdf978abbdb
        '500':
          description: |-
            Server side error i.e connection timeout while talking to downstream services, downstream returned error. The server responds back with this Http "
                      + "response code and with the appropriate JSON error response.
          content:
            application/vnd.exp-activity.v3+json:
              schema:
                $ref: '#/components/schemas/Errors'
        '200':
          description: successful
          content:
            application/vnd.exp-activity.v3+json:
              schema:
                $ref: '#/components/schemas/ActivityDetailsResponse'
              example:
                TransactionId: f06edfa3-27f4-44e6-838c-b8dd3d0a3210
                Count: 1
                Location: shenzhen, gd
                StartDate: 2021-08-01
                EndDate: 2021-08-08
                Categories:
                  - Count: 1
                    CategoryName: Cruises & Water Tours
                    CategoryDisplayName: Cruises & Water Tours
                    GroupName: Tours
                    GroupDisplayName: Tours
                Activities:
                  - Id: 166597
                    Title: 'Faster Than Skip-the-Line: Vatican, Sistine Chapel & St.
                    Peter''s Tour'
                    Description: Enjoy 5 of Seattle's most popular attractions with a multi-ticket booklet that’s valid for 9 consecutive days. This pass is perfect if you want to explore the city on your schedule, craft your own itinerary, and visit the city’s can’t-miss museums and most iconi..
                    Media:
                      - Type: "1"
                        Size: t
                        Url: http://a.travel-assets.com/ lxweb/ media-vault/ 166597_m.jpeg? v=104741
                    Categories:
                      - Walking & Bike Tours
                    Duration: PT3H0M
                    CancellationPolicy:
                      FreeCancellation: true
                    Price:
                      Category: Adult
                      TotalRate:
                        Value: 100
                        Currency: USD
                    ReferencePrice:
                      Category: Adult
                      TotalRate:
                        Value: 110
                        Currency: USD
                    Savings:
                      percentage: 42
                      amount:
                        Value: "9"
                        Currency: USD
                    Redemption:
                      Type: Voucherless
                      Locations:
                        - Address:
                            Address1: 99 Union St
                            City: Seattle
                            PostalCode: "431625"
                            Province: WA
                            Country: USA
                          GeoLocation:
                            Latitude: "47.60772"
                            Longitude: -122.33936
                    Locations:
                      - Address:
                          Address1: 99 Union St
                          City: Seattle
                          PostalCode: "431625"
                          Province: WA
                          Country: USA
                        GeoLocation:
                          Latitude: "47.60772"
                          Longitude: -122.33936
                    Supplier:
                      Name: City Wonders
                    RecommendationScore: 90
                    ReviewCount: 100
                    Links:
                      WebDetails:
                        Href: https://www.expedia.com/things-to-do/space-needle-observation-deck-admission.a193678.activity-details?srp=true&location=sea
                      ApiDetails:
                        Accept: application/vnd.exp-activity.v3+json
                        Method: GET
                        Href: https://apim.expedia.com/activities/details/CgUyMDIzMBIyCgkyMDEzMDQ1OTYSCTIwOTc3MjcwOBoCMjQqCjIwMTctMTEtMTkyCjIwMTctMTEtMjUqAwoBMg
        '404':
          description: No Route matched
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                no Route matched:
                  value: |-
                    {
                        "message": "no Route matched with those values"
                    }
        '429':
          description: API rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                API rate limit exceeded:
                  value: |-
                    {
                        "message": "API rate limit exceeded"
                    }
        '401':
          description: Unauthorized or Invalid authentication credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                unauthorized:
                  value: |-
                    {
                        "message": "Unauthorized"
                    }
                Invalid authentication credentials:
                  value: |-
                    {
                        "message": "Invalid authentication credentials"
                    }
        '403':
          description: cannot consume this service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                cannot consume this service:
                  value: |-
                    {
                        "message": "You cannot consume this service"
                    }
        '503':
          description: name resolution failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIMError'
              examples:
                name resolution failed:
                  value: |-
                    {
                        "message": "name resolution failed"
                    }
        '504':
          description: upstream server is timing out
          content:
            text/plain:
              examples:
                upstream server is timing out:
                  value: The upstream server is timing out
      security:
        - basicSchema: []
components:
  schemas:
    Money:
      required:
        - Currency
        - Value
      type: object
      properties:
        Value:
          type: string
          description: The value of the element being defined.
          example: "21.9"
        Currency:
          type: string
          description: The ISO 4217 Currency Code that the value is expressed in.
          example: USD
        LocalCurrencyPrice:
          $ref: '#/components/schemas/Money'
      description: Container for the discount amount.
    Price:
      required:
        - Category
        - TotalRate
      type: object
      properties:
        Category:
          type: string
          description: |-
            Type of passenger.
            Values supported are:
            ADULT | SENIOR | CHILD
          example: ADULT
        TotalRate:
          $ref: '#/components/schemas/Money'
        TotalFees:
          $ref: '#/components/schemas/Money'
        TotalTaxesAndFees:
          $ref: '#/components/schemas/Money'
        ReferencePrice:
          $ref: '#/components/schemas/ReferencePrice'
        Savings:
          $ref: '#/components/schemas/Savings'
      description: The price of the offer
    ReferencePrice:
      required:
        - TotalRate
      type: object
      properties:
        TotalRate:
          $ref: '#/components/schemas/Money'
        TotalFees:
          $ref: '#/components/schemas/Money'
        TotalTaxesAndFees:
          $ref: '#/components/schemas/Money'
      description: Container for the reference price used for strike out display.
    Restrictions:
      required:
        - Max
        - Min
        - Type
      type: object
      properties:
        Type:
          type: string
          description: Type of the Restriction.
          example: AGE
        Max:
          type: string
          description: Maximum value allowed for the restriction type.
          example: "255"
        Min:
          type: string
          description: Minimum value allowed for the restriction type.
          example: "9"
        Description:
          type: string
          description: The text to describe the restriction.
          example: 9+ years
      description: Container of the Restrictions associated to this ticket.
    Savings:
      required:
        - Amount
        - Percentage
      type: object
      properties:
        Percentage:
          type: integer
          description: The percentage of the price that has been discounted off the regular price for the current activity.
          format: int32
          example: 10
        Amount:
          $ref: '#/components/schemas/Money'
      description: Container of savings information.
    Ticket:
      required:
        - Code
        - Count
        - Id
        - TicketPrice
      type: object
      properties:
        Id:
          type: integer
          description: The numerical identifier for the ticket.
          format: int32
          example: 6429
        Code:
          type: string
          description: |-
            The code for the ticket.
            Values supported are:
            Adult
            Traveler
            Child
            Group
            Senior
            Infant
            Student
          example: Adult
        Count:
          type: integer
          description: The number of each ticket type to be booked.
          format: int32
          example: 1
        Restrictions:
          $ref: '#/components/schemas/Restrictions'
        TicketPrice:
          $ref: '#/components/schemas/Price'
      description: The list of Ticket information.
    Address:
      required:
        - Address1
        - City
        - Country
      type: object
      properties:
        Address1:
          type: string
          description: Street Number, Street Name, or PO Box.
          example: 724 Pine St
        Address2:
          type: string
          description: Apartment, Floor, Suite, Bldg # or more specific information about Address1.
          example: Second Floor
        Suite:
          type: string
          description: Suite/apartment number
          example: "123"
        City:
          type: string
          description: The city
          example: New York
        Province:
          type: string
          description: The state or province.
          example: NY
        Country:
          type: string
          description: 3-letter code for the country.
          example: USA
        PostalCode:
          type: string
          description: Zip/postal code.
          example: "98004"
      description: Address information
    Country:
      required:
        - IsoCode2
        - IsoCode3
        - Name
      type: object
      properties:
        Name:
          type: string
          description: country name
          example: Ireland
        Code:
          type: string
          description: 3-letter code for the country
          example: IRL
        IsoCode2:
          type: string
          description: 2-letter code for the country
          example: IE
        IsoCode3:
          type: string
          description: 3-letter code for the country
          example: IRL
      description: Container for disambiguation country information
    Error:
      required:
        - Code
        - Description
      type: object
      properties:
        Code:
          type: string
          description: Error code describing the issue
          example: AMBIGUOUS_LOCATION
        DetailCode:
          type: string
          description: Detailed error code describing the issue.
          example: MULTIPLE_AMBIGUOUS_LOCATION
        Description:
          type: string
          description: A simple description of what the error is.
          example: 'Multiple pickup locations found. '
        LocationKeyword:
          type: string
          description: The requested location that caused the error.
          example: 'Portland. '
        LocationOptions:
          type: array
          description: 'List for possible locations from which the customer must choose
            the best one to be re-submitted in the request. '
          items:
            $ref: '#/components/schemas/LocationOption'
      description: Container for error list.
    Errors:
      required:
        - Errors
        - TransactionId
      type: object
      properties:
        Errors:
          type: array
          description: Container for error list.
          items:
            $ref: '#/components/schemas/Error'
        TransactionId:
          type: string
          description: A unique identifier for the transaction.
          example: a9e371c4-89d9-4f9c-8df7-df105830e7fe
      xml:
        name: ErrorResponse
    GeoLocation:
      required:
        - Latitude
        - Longitude
      type: object
      properties:
        Latitude:
          type: string
          description: Latitude of the location.
          example: "38.184978"
        Longitude:
          type: string
          description: Longitude of the location.
          example: "85.7412"
        Obfuscated:
          type: boolean
      description: Geographic information
    Location:
      type: object
      properties:
        Type:
          type: string
          description: The type of location code (MULTICITY | METROCODE).
          example: MULTICITY
        Id:
          type: string
          description: Expedia Region ID of the specified airport.
          example: "6139103"
        Name:
          type: string
          description: Location Name
          example: Seattle-Tacoma International Airport
        Code:
          type: string
          description: Location Code
          example: SEA
        LocationId:
          type: string
          description: Location id.
          example: SEAT001
        Address:
          $ref: '#/components/schemas/Address'
        PointOfInterest:
          type: string
        GeoLocation:
          $ref: '#/components/schemas/GeoLocation'
        Neighborhood:
          $ref: '#/components/schemas/Neighborhood'
        RegionId:
          type: integer
          description: RegionId the location resides in.
          format: int64
          example: 6200275
        Country:
          $ref: '#/components/schemas/Country'
      description: List of location(s) where the activity will happen.
    LocationOption:
      required:
        - Locations
        - RequestedLocation
      type: object
      properties:
        RequestedLocation:
          type: string
          description: Location used in partner request.
          example: Paris
        Locations:
          type: array
          description: Container for list of possible locations that could be used to disambiguate the query.
          items:
            $ref: '#/components/schemas/Location'
        Type:
          type: string
          description: Type of the location.
          example: TRAINSTATION
        RegionId:
          type: string
          description: RegionId the location resides in.
          example: "6200275"
        ShortName:
          type: string
          description: The name of the location which matches the location keyword.
          example: Dublin Connolly Station
        AirportCode:
          type: string
          description: Indicates the nearest major airport to the location.
          example: DUB
        Address:
          type: string
          description: The address of the location.
          example: Dublin Connolly Station, Ireland
        Country:
          $ref: '#/components/schemas/Country'
        GeoLocation:
          $ref: '#/components/schemas/GeoLocation'
      description: 'List for possible locations from which the customer must choose
        the best one to be re-submitted in the request. '
    Neighborhood:
      required:
        - Id
        - Name
      type: object
      properties:
        Id:
          type: string
          description: Neighborhood id.
          example: "6160232"
        Name:
          type: string
          description: Neighborhood name.
          example: Le Pharo
      description: Geography entities which are typically contained within a city. This includes the categories neighborhood and point of interest. Low level regions are not a formally defined concept in the geography model.
    Activity:
      required:
        - Categories
        - Description
        - Duration
        - FreeCancellation
        - Id
        - Media
        - Price
        - Supplier
        - Title
      type: object
      properties:
        Id:
          type: integer
          description: The numerical identifier for this particular activity
          format: int32
          example: 166597
        Title:
          type: string
          description: The display title for this activity.
          example: 'Faster Than Skip-the-Line: Vatican, Sistine Chapel & St. Peter''s
            Tour'
        Description:
          type: string
          description: The description of the Activity.
          example: Enjoy 5 of Seattle's most popular attractions with a multi-ticket booklet that’s valid for 9 consecutive days. This pass is perfect if you want to explore the city on your schedule, craft your own itinerary, and visit the city’s can’t-miss museums and most iconi...
        Media:
          type: array
          description: List of activity Media.
          items:
            $ref: '#/components/schemas/Media'
        Categories:
          type: array
          description: |-
            A list of the Activity categories to which this particular activity belongs.
            Possible values are:
            Adventures
            Air, Balloon & Helicopter Tours
            Attractions
            Cruises & Water Tours
            Day Trips & Excursions
            Food & Drink
            Hop-on Hop-off
            Multi-Day & Extended Tours
            Nightlife
            Private Tours
            Private Transfers
            Shared Transfers
            Show & Sport Tickets
            Sightseeing Passes
            Theme Parks
            Tours & Sightseeing
            Walking & Bike Tours
            Water Activities
            Wedding Ceremonies
            Winter Activities
          example:
            - Walking & Bike Tours
          items:
            type: string
            description: A list of the Activity categories to which this particular activity belongs.
            example: Walking & Bike Tours
            xml:
              name: Categories
        Duration:
          type: string
          description: |-
            The anticipated time duration for the activity.
            Using java jdk Duration parsing.
          example: PT1H0M
        FreeCancellation:
          type: boolean
          description: A boolean value describing whether or not this activity reservation can be cancelled without incurring a penalty.
          example: true
        Price:
          $ref: '#/components/schemas/Price'
        Redemption:
          $ref: '#/components/schemas/Redemption'
        ActivityLocations:
          type: array
          description: Container of location information where activity happens.
          items:
            $ref: '#/components/schemas/Location'
        Supplier:
          $ref: '#/components/schemas/Supplier'
        ReviewScore:
          type: integer
          description: The overall Expedia score for the activity.
          format: int32
          example: 72
        ReviewCount:
          type: integer
          description: The number of Expedia reviews that went into the calculation of the ReviewScore.
          format: int32
          example: 19
        Links:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Link'
          description: HATEOAS links included in this response.
          xml:
            wrapped: true
        CancellationPolicy:
          $ref: '#/components/schemas/CancellationPolicy'
        Highlights:
          type: array
          description: Web formatted statement of the Highlight(s) for the activity.
          items:
            type: string
            description: Web formatted statement of the Highlight(s) for the activity.
            xml:
              name: Highlights
        TermsAndConditions:
          type: array
          description: Terms and Conditions for the Activity.
          items:
            type: string
            description: Terms and Conditions for the Activity.
            xml:
              name: TermsAndConditions
        Inclusions:
          type: array
          description: Web formatted statement of what is included in the activity
          items:
            type: string
            description: Web formatted statement of what is included in the activity
            xml:
              name: Inclusions
        Exclusions:
          type: array
          description: Web formatted statement of what is NOT included in the activity
          items:
            type: string
            description: Web formatted statement of what is NOT included in the activity
            xml:
              name: Exclusions
        KnowBeforeYouBook:
          type: array
          description: Web formatted statement of things that a purchaser should be aware of BEFORE they book this activity.
          items:
            type: string
            description: Web formatted statement of things that a purchaser should be aware of BEFORE they book this activity.
            xml:
              name: KnowBeforeYouBook
        KnowBeforeYouGo:
          type: array
          description: Web formatted statement of things that a purchaser should be aware of BEFORE they go to this activity.
          items:
            type: string
            description: Web formatted statement of things that a purchaser should be aware of BEFORE they go to this activity.
            xml:
              name: KnowBeforeYouGo
        Offers:
          type: array
          description: Offers for the activity.
          items:
            $ref: '#/components/schemas/Offer'
      description: Detailed information on the Activity.
    AvailableTimeSlot:
      required:
        - AllDayActivity
        - CancellationPolicy
        - DateTime
        - Tickets
      type: object
      properties:
        DateTime:
          type: string
          description: The date and time when the activity happens.
          format: date-time
        AllDayActivity:
          type: boolean
          description: Indicates whether the activity is an all-day activity.
          example: true
        CancellationPolicy:
          $ref: '#/components/schemas/CancellationPolicy'
        Tickets:
          type: array
          description: Container for ticket information.
          items:
            $ref: '#/components/schemas/Ticket'
      description: The list of available Time Slots for the activity.
    CancellationPolicy:
      required:
        - FreeCancellation
      type: object
      properties:
        FreeCancellation:
          type: boolean
          description: Indicates whether the activity can be canceled free of charge within the cancellation window or not.
          example: true
        CancelPolicyDescription:
          type: string
          description: The description of Cancellation Policy.
          example: 72 hours
        FreeCancellationMinHours:
          type: integer
          description: The minimum number of hours before activity when the activity can still be cancelled for free.
          format: int32
          example: 72
        FreeCancellationEndDateTime:
          type: string
          description: The date and time after which the activity will not be able to be cancelled for free, stated in the local time to where the activity takes place.
          format: date-time
      description: Container for the Cancellation Policy information.
    Link:
      required:
        - Href
      type: object
      properties:
        Accept:
          type: string
          description: Accept header.
        Method:
          type: string
          description: HTTP method to connect.
          example: GET
        Href:
          type: string
          description: HATEOAS URL to fetch details.
      description: Container of HATEOAS URL's
    Media:
      required:
        - Size
        - Type
        - Url
      type: object
      properties:
        Type:
          type: string
          description: |-
            type of the media. So far there is only one option:
            1: Image
          example: "1"
        Title:
          type: string
          description: Image title
          example: Guestroom
        Size:
          type: string
          description: |-
            Image size
            You can find a link to the complete list of Supported Images Sizes in the Related Links section at the bottom of the page.
          example: t
        Url:
          type: string
          description: Image URL
          example: https://images.trvl-media.com/hotels/1000000/30000/20300/20230/20230_159_t.jpg
      description: List of activity Media.
    Offer:
      required:
        - AvailableTimeSlots
        - Description
        - Duration
        - Id
        - OfferPrice
        - Title
      type: object
      properties:
        Id:
          type: integer
          description: The numerical identifier for the offer.
          format: int32
          example: 166597
        Title:
          type: string
          description: A descriptive title for this offer.
          example: 8:30 AM, Tour in English
        Description:
          type: string
          description: Description of this offer.
        Duration:
          type: string
          description: The anticipated time duration for the activity, e xpressed using Java JDK duration format.
        AvailableTimeSlots:
          type: array
          description: The list of available Time Slots for the activity.
          items:
            $ref: '#/components/schemas/AvailableTimeSlot'
        OfferPrice:
          $ref: '#/components/schemas/Price'
        Links:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Link'
          description: Container of HATEOAS URL's
          xml:
            wrapped: true
      description: Offers for the activity.
    Phone:
      required:
        - CountryCode
        - Number
      type: object
      properties:
        CountryCode:
          type: string
          description: Country code of traveler's phone number; only digits allowed.
          example: "1"
        AreaCode:
          type: string
          description: Area code of traveler's phone number; only digits allowed.
          example: "614"
        Number:
          type: string
          description: Traveler's phone number; only digits allowed.
          example: "9288472"
        ExtensionNumber:
          type: string
      description: The phone of the company providing the activity.
    Redemption:
      type: object
      properties:
        Type:
          type: string
          description: The type of redemption process associated to the activity.
          example: Voucherless
        RedemptionLocations:
          type: array
          description: List of redemption locations where the activity will take place, please refer to Location Section below.
          items:
            $ref: '#/components/schemas/Location'
      description: Container of redemption information.
    Supplier:
      required:
        - Name
      type: object
      properties:
        Name:
          type: string
          description: The name of the company providing the activity.
          example: City Wonders
        Phone:
          $ref: '#/components/schemas/Phone'
      description: The details information of company providing the activity.
    Warning:
      required:
        - Code
        - Description
      type: object
      properties:
        Code:
          type: string
          description: Standardized warning code.
          example: INVALID_CORPORATE_DISCOUNT_CODE
        Description:
          type: string
          description: Standardized warning description message.
          example: The Corporate DiscountCode '811490' is unavailable, but we found other rates for you.
        OriginalPrice:
          $ref: '#/components/schemas/Money'
        NewPrice:
          $ref: '#/components/schemas/Money'
        ChangedAmount:
          $ref: '#/components/schemas/Money'
        ChangedPercentage:
          type: string
          description: |-
            The changed percentage.
            In the sample 2.97 means the changed percentage is 2.97%.
          example: "2.97"
        Links:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Link'
          xml:
            wrapped: true
      description: Container for all warnings generated during the transaction.
    ActivityListingsResponse:
      required:
        - Count
        - Location
        - TransactionId
      type: object
      properties:
        Warnings:
          type: array
          description: Container for all warnings generated during the transaction.
          items:
            $ref: '#/components/schemas/Warning'
        TransactionId:
          type: string
          description: A unique identifier for this transaction.
          example: f06edfa3-27f4-44e6-838c-b8dd3d0a3210
        Count:
          type: integer
          description: The number of activities returned in the response.
          format: int64
          example: 100
        Location:
          type: string
          description: The location that the user searched, expressed in the exact format that the inventory system uses to designate the location.
          example: shenzhen, dg
        StartDate:
          type: string
          description: The startDate of the returned group of activities in YYYY-MM-DD format.
          format: date
          example: 2021-08-01
        EndDate:
          type: string
          description: The endDate of returned group of activities in YYYY-MM-DD format.
          format: date
          example: 2021-08-10
        Activities:
          type: array
          description: List of activities matching the search criteria.
          items:
            $ref: '#/components/schemas/Activity'
        Categories:
          type: array
          description: Container for a breakdown of how many of each type of Activity have been returned in the API response.
          items:
            $ref: '#/components/schemas/CategoryGroup'
    CategoryGroup:
      required:
        - CategoryName
        - Count
        - GroupDisplayName
        - GroupName
      type: object
      properties:
        Count:
          type: integer
          description: The count of the number of categories the returned set of activities map to.
          format: int32
          example: 10
        GroupName:
          type: string
          description: |-
            The group which the category belongs
            Possible value is:
            Recommendations
            Tours
            Activities
            Transportation
            Promotions
            Duration
          example: Tours
        GroupDisplayName:
          type: string
          description: The localized value for category name.
          example: Wander- und Fahrradtouren
        CategoryName:
          type: string
          description: The name of one of the categories.
          example: Walking & Bike Tours
        CategoryDisplayName:
          type: string
      description: Container for a breakdown of how many of each type of Activity have been returned in the API response.
    ActivityDetailsResponse:
      required:
        - Location
        - TransactionId
      type: object
      properties:
        Warnings:
          type: array
          description: Container for all warnings generated during the transaction.
          items:
            $ref: '#/components/schemas/Warning'
        TransactionId:
          type: string
          description: A unique identifier for this transaction.
          example: f06edfa3-27f4-44e6-838c-b8dd3d0a3210
        Location:
          type: string
          description: The location user searched, translated into the full, unambiguous format.
          example: shenzhen, dg
        StartDate:
          type: string
          description: The startDate of activities in YYY-MM-DD format.
          format: date
          example: 2021-08-01
        EndDate:
          type: string
          description: The endDate of activities in YYY-MM-DD format.
          format: date
          example: 2021-08-01
        ActivityDetails:
          $ref: '#/components/schemas/Activity'
    APIMError:
      title: APIMError
      properties:
        message:
          type: string
  securitySchemes:
    basicSchema:
      type: http
      scheme: basic
